language: php

php:
  - 5.3.3
  - 5.5

install:
  - php composer.phar install --dev --no-interaction --prefer-source

before_script:
  - vendor/bin/phing prepare_test -Dversion=HEAD

script:
  - vendor/bin/phing test -Dversion=HEAD -Dlanguage=de
  - vendor/bin/phing test -Dversion=HEAD -Dlanguage=de_x_sie
